require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Layout/LineLength:
  Max: 120
Layout/HashAlignment:
  Enabled: false
Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false
Layout/ArrayAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/WhileUntilModifier:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/LetBeforeExamples:
  Enabled: false
